"""Tests for WAF & Silent AI Crawler Blockage Probe."""

import pytest
from answrank.audit.waf_probe import WAFProbeEngine, WAFRiskLevel, WAFProbeResult


def test_waf_signatures_defined():
    assert len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS) >= 6
    assert "OAI-SearchBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    assert "GPTBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    assert "PerplexityBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    assert "Claude-SearchBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    # 2026 answer engines present in the WAF probe roster:
    assert "xAI-SearchBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    assert "Kimi-SearchBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS
    assert "Amzn-SearchBot" in WAFProbeEngine.AI_CRAWLER_USER_AGENTS


@pytest.mark.anyio
async def test_waf_probe_offline_simulation(monkeypatch):
    """Test WAF probe result calculation when all bots return 200 OK."""
    async def mock_get(*args, **kwargs):
        class MockResp:
            status_code = 200
            text = "<html><body><h1>Welcome</h1></body></html>"
            headers = {}
        return MockResp()

    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_get)

    res: WAFProbeResult = await WAFProbeEngine.probe_url("https://example.com")
    assert res.overall_risk == WAFRiskLevel.LOW
    assert res.is_silently_blocked is False
    assert res.accessible_bots_count == len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS)
    assert res.blocked_bots_count == 0


@pytest.mark.anyio
async def test_waf_probe_cloudflare_detection(monkeypatch):
    """Test WAF probe detecting Cloudflare Turnstile challenge."""
    async def mock_cf_get(*args, **kwargs):
        class MockResp:
            status_code = 403
            text = "<html><body><h1>Attention Required! | Cloudflare</h1></body></html>"
            headers = {"cf-mitigated": "challenge"}
        return MockResp()

    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_cf_get)

    res: WAFProbeResult = await WAFProbeEngine.probe_url("https://blocked-site.com")
    assert res.overall_risk == WAFRiskLevel.CRITICAL
    assert res.is_silently_blocked is True
    assert res.blocked_bots_count == len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS)
    assert "Cloudflare" in (res.detected_waf_provider or "")

# --- Branch coverage: URL normalization, Wordfence, Imperva, exception, MEDIUM risk ---

@pytest.mark.anyio
async def test_waf_probe_url_normalization(monkeypatch):
    """URL without scheme gets https:// prefixed."""
    async def mock_get(*args, **kwargs):
        class MockResp:
            status_code = 200
            text = "<html><body><h1>Welcome</h1></body></html>"
            headers = {}
        return MockResp()
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_get)
    res = await WAFProbeEngine.probe_url("bare-domain.com")
    assert res.target_url == "https://bare-domain.com"

@pytest.mark.anyio
async def test_waf_probe_wordfence_detection(monkeypatch):
    """Wordfence block signature detection."""
    async def mock_wf_get(*args, **kwargs):
        class MockResp:
            status_code = 403
            text = "<html><body><h1>Your access to this site has been limited. Generated by WordFence</h1></body></html>"
            headers = {}
        return MockResp()
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_wf_get)
    res = await WAFProbeEngine.probe_url("https://wordfence-blocked.com")
    assert res.overall_risk == WAFRiskLevel.CRITICAL
    assert res.detected_waf_provider == "Wordfence Security WAF"
    assert all(s.blocking_signature == "Wordfence IP Block" for s in res.bot_statuses)
    assert "Wordfence" in res.remediation_recommendation

@pytest.mark.anyio
async def test_waf_probe_imperva_detection(monkeypatch):
    """Imperva/Incapsula signature via response header."""
    async def mock_imp_get(*args, **kwargs):
        class MockResp:
            status_code = 403
            text = "<html><body><h1>OK</h1></body></html>"
            headers = {"X-Iinfo": "incapsula-incident-12345"}
        return MockResp()
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_imp_get)
    res = await WAFProbeEngine.probe_url("https://imperva-site.com")
    assert res.detected_waf_provider == "Imperva / Incapsula WAF"
    assert all(s.blocking_signature == "Imperva Incident Mitigation" for s in res.bot_statuses)

@pytest.mark.anyio
async def test_waf_probe_target_unreachable_is_unverified(monkeypatch):
    """If even the baseline browser request cannot connect, the probe must NOT
    accuse the site of WAF blocking — it returns UNVERIFIED with zero blocks."""
    async def mock_boom(*args, **kwargs):
        raise TimeoutError("connection timed out after 6s")
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_boom)
    res = await WAFProbeEngine.probe_url("https://unreachable.example")
    roster = len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS)
    assert res.overall_risk == WAFRiskLevel.UNVERIFIED
    assert res.is_silently_blocked is False
    assert res.blocked_bots_count == 0
    assert res.unreachable_bots_count == roster
    assert res.baseline_reachable is False
    assert all(s.status_code == 0 for s in res.bot_statuses)
    assert all("Connection/Timeout Error" in (s.blocking_signature or "") for s in res.bot_statuses)
    assert "hüküm veremedi" in res.remediation_recommendation


@pytest.mark.anyio
async def test_waf_probe_silent_drop_while_browser_ok_is_critical(monkeypatch):
    """Baseline browser gets 200 but every bot UA connection is dropped -> the
    original 'silent blocking' detection must still fire CRITICAL."""
    async def mock_drop(*args, **kwargs):
        ua = (kwargs.get("headers") or {}).get("User-Agent", "")
        if "Chrome/120.0.0.0" in ua:  # baseline browser request
            class MockResp:
                status_code = 200
                text = "<html><body>ok</body></html>"
                headers = {}
            return MockResp()
        raise ConnectionResetError("connection reset by peer")
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_drop)
    res = await WAFProbeEngine.probe_url("https://silent-drop.example")
    roster = len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS)
    assert res.overall_risk == WAFRiskLevel.CRITICAL
    assert res.is_silently_blocked is True
    assert res.blocked_bots_count == roster
    assert res.unreachable_bots_count == roster  # dropped at connection level
    assert res.baseline_reachable is True
    assert all("Silent connection drop" in (s.blocking_signature or "") for s in res.bot_statuses)


@pytest.mark.anyio
async def test_waf_probe_baseline_5xx_server_error_still_blocks(monkeypatch):
    """A target answering 503 to everyone IS reachable (server responds) and its
    pages are unreadable by AI bots — that is an AEO-blocking condition, so the
    probe keeps CRITICAL semantics (not UNVERIFIED, which is connection-level only)."""
    async def mock_5xx(*args, **kwargs):
        class MockResp:
            status_code = 503
            text = "service unavailable"
            headers = {}
        return MockResp()
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_5xx)
    res = await WAFProbeEngine.probe_url("https://broken.example")
    assert res.baseline_reachable is True
    assert res.overall_risk == WAFRiskLevel.CRITICAL
    assert res.blocked_bots_count == len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS)


@pytest.mark.anyio
async def test_waf_probe_medium_risk(monkeypatch):
    """One rate-limited bot (429 without WAF signature), rest 200 -> MEDIUM."""
    async def mock_rate_limit(*args, **kwargs):
        ua = (kwargs.get("headers") or {}).get("User-Agent", "")
        class MockResp:
            status_code = 429 if "GPTBot" in ua else 200
            text = "<html><body><h1>Welcome</h1></body></html>"
            headers = {}
        return MockResp()
    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_rate_limit)
    res = await WAFProbeEngine.probe_url("https://ratelimited.com")
    assert res.overall_risk == WAFRiskLevel.MEDIUM
    assert res.is_silently_blocked is True
    assert res.blocked_bots_count == 1
    assert res.accessible_bots_count == len(WAFProbeEngine.AI_CRAWLER_USER_AGENTS) - 1
    assert "UYARI" in res.remediation_recommendation


@pytest.mark.anyio
async def test_waf_probe_medium_with_network_error_part(monkeypatch):
    """Baseline reachable + a bot-level exception (below the critical
    threshold) must render MEDIUM that counts network errors separately —
    honest partial evidence, not accusation, not silence."""
    flaky_ua = list(WAFProbeEngine.AI_CRAWLER_USER_AGENTS.values())[0]

    class OkResp:
        status_code = 200
        text = "<html><body><h1>Welcome</h1></body></html>"
        headers = {}

    async def mock_mixed(*args, **kwargs):
        ua = (kwargs.get("headers") or {}).get("User-Agent", "")
        if ua == flaky_ua:
            raise ConnectionError("one unlucky bot timed out")
        return OkResp()

    import httpx
    monkeypatch.setattr(httpx.AsyncClient, "get", mock_mixed)
    res = await WAFProbeEngine.probe_url("https://flakysite.com")
    assert res.baseline_reachable is True
    assert res.overall_risk == WAFRiskLevel.MEDIUM
    assert res.unreachable_bots_count == 1
    assert res.blocked_bots_count == 1  # browser-OK + bot-drop = genuine silent block (below critical threshold)
    assert res.is_silently_blocked is True
    assert "ağ hatası verdi" in res.remediation_recommendation
    assert "engellendi" in res.remediation_recommendation
