"""WAF & Silent AI Crawler Blockage Probe for AnswRank.

Detects network-layer and CDN/WAF blocking (Cloudflare Turnstile, 403 Forbidden,
Wordfence, Imperva) against 6 core AI search and citation crawlers.
"""

import httpx
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class WAFRiskLevel(str, Enum):
    LOW = "LOW"              # Fully accessible to AI crawlers
    MEDIUM = "MEDIUM"        # Some rate limits or challenge hints detected
    CRITICAL = "CRITICAL"    # Silent blockage (403 or JS Challenge) on active AI bots
    UNVERIFIED = "UNVERIFIED"  # Majority of probes got no HTTP response (site down / DNS /
                               # timeout) — a blockage verdict is impossible; never reported
                               # as a block, because that would accuse unreachable sites.


class BotProbeStatus(BaseModel):
    bot_name: str
    user_agent: str
    status_code: int
    is_accessible: bool
    is_cloudflare_challenge: bool
    is_waf_blocked: bool
    blocking_signature: Optional[str] = None
    response_time_ms: float = 0.0


class WAFProbeResult(BaseModel):
    target_url: str
    overall_risk: WAFRiskLevel
    is_silently_blocked: bool
    accessible_bots_count: int
    blocked_bots_count: int
    total_probed: int = 0
    unreachable_bots_count: int = 0
    baseline_reachable: Optional[bool] = None
    detected_waf_provider: Optional[str] = None
    bot_statuses: List[BotProbeStatus] = Field(default_factory=list)
    remediation_recommendation: str


class WAFProbeEngine:
    """Probes web targets using real AI bot User-Agents to detect silent blocking."""

    AI_CRAWLER_USER_AGENTS = {
        "OAI-SearchBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; OAI-SearchBot/1.0; +https://openai.com/searchbot)",
        "GPTBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.2; +https://openai.com/gptbot)",
        "PerplexityBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)",
        "Claude-SearchBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-SearchBot/1.0; +https://anthropic.com/claude-searchbot)",
        "ClaudeBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +https://anthropic.com/claudebot)",
        "Google-Extended": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Google-Extended/1.0)",
        # Added 15 Sept 2026 — exact UA strings copied from knownagents.com agent pages:
        "xAI-SearchBot": "Mozilla/5.0 (compatible; xAI-SearchBot/1.0; +https://x.ai)",
        "Kimi-SearchBot": "Mozilla/5.0 (compatible; Kimi-SearchBot/1.0; +https://kimi.ai/)",
        "Amzn-SearchBot": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amzn-SearchBot/0.1) Chrome/119.0.6045.214 Safari/537.36",
    }

    CLOUDFLARE_SIGNATURES = [
        "cf-mitigated",
        "attention required! | cloudflare",
        "just a moment...",
        "__cf_chl_",
        "cloudflare ray id",
    ]

    WORDFENCE_SIGNATURES = [
        "generated by wordfence",
        "your access to this site has been limited",
        "blocked by wordfence",
    ]

    IMPERVA_SIGNATURES = [
        "x-iinfo",
        "incapsula",
        "request unsuccessful. incapsula incident",
    ]

    @classmethod
    async def probe_url(cls, url: str, timeout_sec: float = 6.0,
                    bots: Optional[List[str]] = None) -> WAFProbeResult:
        """Asynchronously probe URL with the configured AI-bot User-Agent roster.

        A baseline regular-browser request runs first: if the target does not answer
        that either, the probe is reported UNVERIFIED instead of a block — an offline
        or unreachable site is never accused of 'WAF silent blocking'.

        `bots` (E3): optional roster subset — the public mini-probe probes three
        representative bots instead of burning all nine per request. Unknown names
        are ignored; None means the full registry.
        """
        roster = (cls.AI_CRAWLER_USER_AGENTS if bots is None
                  else {k: v for k, v in cls.AI_CRAWLER_USER_AGENTS.items() if k in bots})
        if not url.startswith(("http://", "https://")):
            url = "https://" + url

        statuses: List[BotProbeStatus] = []
        detected_waf = None

        async with httpx.AsyncClient(timeout=timeout_sec, follow_redirects=True) as client:
            # 0. Baseline reachability probe with an ordinary browser UA.
            # Any HTTP answer (even 5xx) proves the target is alive; only a
            # connection-level failure means no verdict can be given.
            baseline_reachable: Optional[bool] = None
            try:
                await client.get(url, headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                })
                baseline_reachable = True
            except Exception:
                baseline_reachable = False

            for bot_name, ua in roster.items():
                headers = {
                    "User-Agent": ua,
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                    "Accept-Language": "tr,en-US;q=0.9,en;q=0.8",
                }
                try:
                    import time
                    start_t = time.time()
                    resp = await client.get(url, headers=headers)
                    duration_ms = round((time.time() - start_t) * 1000, 1)

                    body_lower = resp.text.lower()
                    headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}

                    # Check for WAF Signatures
                    is_cf = any(sig in body_lower or sig in str(headers_lower) for sig in cls.CLOUDFLARE_SIGNATURES)
                    is_wf = any(sig in body_lower for sig in cls.WORDFENCE_SIGNATURES)
                    is_imp = any(sig in body_lower or sig in str(headers_lower) for sig in cls.IMPERVA_SIGNATURES)

                    blocking_sig = None
                    if is_cf:
                        detected_waf = detected_waf or "Cloudflare (Bot Management / Turnstile)"
                        blocking_sig = "Cloudflare Challenge / Managed Challenge"
                    elif is_wf:
                        detected_waf = detected_waf or "Wordfence Security WAF"
                        blocking_sig = "Wordfence IP Block"
                    elif is_imp:
                        detected_waf = detected_waf or "Imperva / Incapsula WAF"
                        blocking_sig = "Imperva Incident Mitigation"

                    is_blocked = (resp.status_code in [401, 403, 429, 503]) or (is_cf and resp.status_code != 200)
                    is_accessible = (resp.status_code == 200) and not is_cf and not is_wf and not is_imp

                    statuses.append(
                        BotProbeStatus(
                            bot_name=bot_name,
                            user_agent=ua,
                            status_code=resp.status_code,
                            is_accessible=is_accessible,
                            is_cloudflare_challenge=is_cf,
                            is_waf_blocked=is_blocked,
                            blocking_signature=blocking_sig,
                            response_time_ms=duration_ms,
                        )
                    )
                except Exception as e:
                    # Connection error interpretation depends on the baseline:
                    # - browser gets through, bot UA dropped  -> SILENT BLOCK (real signal)
                    # - browser cannot get through either      -> unreachable, no verdict
                    silent_drop = bool(baseline_reachable)
                    statuses.append(
                        BotProbeStatus(
                            bot_name=bot_name,
                            user_agent=ua,
                            status_code=0,
                            is_accessible=False,
                            is_cloudflare_challenge=False,
                            is_waf_blocked=silent_drop,
                            blocking_signature=(
                                "Silent connection drop (tarayıcı erişirken bot isteği düşürüldü)"
                                if silent_drop else f"Connection/Timeout Error: {str(e)[:60]}"
                            ),
                            response_time_ms=0.0,
                        )
                    )

        accessible_count = sum(1 for s in statuses if s.is_accessible)
        unreachable_count = sum(1 for s in statuses if s.status_code == 0)
        blocked_count = sum(1 for s in statuses if s.is_waf_blocked)
        total_bots = len(statuses)
        # CRITICAL when at least half of the probe roster is blocked (absolute
        # floor of 3 so a single outlier never trips it); threshold scales with
        # roster size and can never drift when bots are added/removed.
        critical_threshold = max(3, (total_bots + 1) // 2)

        if baseline_reachable is False:
            # Even an ordinary browser got no usable response — no verdict possible.
            risk = WAFRiskLevel.UNVERIFIED
            silently_blocked = False
            rec = (
                "Probe hüküm veremedi: hedef site olağan bir tarayıcı isteğine de karşılık "
                "vermedi (site kapalı, DNS hatası veya timeout). WAF blokajı hakkında karar "
                "verilemez — lütfen daha sonra yeniden probe edin."
            )
        elif blocked_count >= critical_threshold:
            risk = WAFRiskLevel.CRITICAL
            silently_blocked = True
            rec = (
                f"KRİTİK UYARI: Hedef web sitesi {blocked_count}/{total_bots} AI botunu ağ seviyesinde engelliyor "
                f"({detected_waf or 'Bilinmeyen WAF'}). robots.txt'te izin verilmiş olsa bile botlar "
                f"sayfayı okuyamamaktadır. Cloudflare WAF Security ayarlarında AI botlarına 'Bypass/Allow' kuralı tanımlanmalıdır."
            )
        elif blocked_count > 0 or unreachable_count > 0:
            risk = WAFRiskLevel.MEDIUM
            silently_blocked = blocked_count > 0
            parts = []
            if blocked_count > 0:
                parts.append(f"{blocked_count} bot HTTP katmanında engellendi")
            if unreachable_count > 0:
                parts.append(f"{unreachable_count} istek ağ hatası verdi (muhtemel rate-limit/timeout)")
            rec = f"UYARI: {'; '.join(parts)}. WAF veya rate-limit istisnalarının genişletilmesi önerilir."
        else:
            risk = WAFRiskLevel.LOW
            silently_blocked = False
            rec = f"Tüm {total_bots} AI arama botu web sitesine ağ katmanında engelsiz erişebilmektedir. WAF blokaj riski sıfırdır."

        return WAFProbeResult(
            target_url=url,
            overall_risk=risk,
            is_silently_blocked=silently_blocked,
            accessible_bots_count=accessible_count,
            blocked_bots_count=blocked_count,
            total_probed=total_bots,
            unreachable_bots_count=unreachable_count,
            baseline_reachable=baseline_reachable,
            detected_waf_provider=detected_waf,
            bot_statuses=statuses,
            remediation_recommendation=rec,
        )
